ajax/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from ajax.views import (
                GetVaildNameView,
                GetVaildUserNameView,
)

urlpatterns = [
        path('check_name/', GetVaildNameView.as_view()),
        path('check_username/', GetVaildUserNameView.as_view()),
]

cart/api/urls.py
from django.urls import path


from cart.api import views


app_name = "cart_api"

urlpatterns = [
        path('create/', views.CratItemCreateApiView.as_view(), name='cart_create'),
        path('cartitem_list/', views.CratItemListApiView.as_view(), name='cartitem_list'),
        path('checkout/', views.CartCheckOutApiView.as_view(), name='cart_checkout'),
        path('list/', views.CartListApiView.as_view(), name='cart_list'),
        path('detail/<int:id>/', views.CartDetailApiView.as_view(), name='cart_detail'),
]

cart/urls.py
from django.urls import path
from .views import (
            CartCreateView,
            CartCheckOutView,
            CartHistoryView,
            CartDetailView,
)

app_name = "cart"

urlpatterns = [
    path('create/', CartCreateView.as_view(), name='create'),
    path('history/', CartHistoryView.as_view(), name='cart_history'),
    path('checkout/', CartCheckOutView.as_view(), name='checkout'),
    path('detail/<int:id>/', CartDetailView.as_view(), name='cart_detail'),
]

main/urls.py
from django.urls import path
from .views import (
                TaggedView,

                ManufacturerListView,
                ManufacturerDetailView,
                ManufacturerCreateView,
                ManufacturerUpdateView,
                ManufacturerDeleteView,

                CategoryListView,
                CategoryCreateView,
                CategoryUpdateView,
                CategoryDeleteView,

                ProductListView,
                ProductDetailView,
                ProductCreateView,
                ProductUpdateView,
                ProductDeleteView,
)

app_name = "main"

urlpatterns = [
    # Tagged urls
    path('tag/<slug:slug>/', TaggedView.as_view(), name="tagged"),

    #  Product Urls
    path('product/list/',              ProductListView.as_view(),   name='product_list'),
    path('product/create/',            ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:id>/',   ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:id>/',   ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:id>/',   ProductDeleteView.as_view(), name='product_delete'),


    #  Category Urls
    path('category/list/',            CategoryListView.as_view(),   name='category_list'),
    path('category/create/',          CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:id>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:id>/', CategoryDeleteView.as_view(), name='category_delete'),

    #  Manufacturer Urls
    path('manufacturer/list/',            ManufacturerListView.as_view(),   name='manufacturer_list'),
    path('manufacturer/create/',          ManufacturerCreateView.as_view(), name='manufacturer_create'),
    path('manufacturer/detail/<int:id>/', ManufacturerDetailView.as_view(), name='manufacturer_detail'),
    path('manufacturer/update/<int:id>/', ManufacturerUpdateView.as_view(), name='manufacturer_update'),
    path('manufacturer/delete/<int:id>/', ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from user.views import (
            UserLoginView,
            UserLogoutView,
            UserSignUpView,
            UserActivation,
            UserForgotPasswordView,
            UserForgotPassword,
            UserChangePasswordView,
)

app_name = 'user'

urlpatterns = [
    path('login/',  UserLoginView.as_view(),  name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('forgot_password/', UserForgotPasswordView.as_view(), name='forgot_password'),
    path('change_password/', UserChangePasswordView.as_view(), name='change_password'),
    path('reset_password/uid=<str:uid>', UserForgotPassword.as_view(), name='reset_password'),
    path('activate/uid=<str:uidb64>/token=<str:token>',UserActivation.as_view(), name='activate'),
    path('forgot_password_check/uid=<str:uidb64>/token=<str:token>', UserForgotPassword.as_view(), name='forgot_password_check'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime
from main.models import Product

class Cart(models.Model):
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)
    checkout = models.BooleanField(default=False)
    total_price = models.CharField(max_length=300, default="0")
    total_item = models.PositiveIntegerField(default=0)
    success_code = models.CharField(max_length=256, null=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('Cart:cart_detail', kwargs={'id':self.id})



class CartItem(models.Model):
    cart        = models.ForeignKey(Cart, on_delete=models.CASCADE )
    product     = models.ForeignKey(Product, on_delete=models.CASCADE)
    price       = models.CharField(max_length=300)
    quantity    = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.price

cart/api/views.py
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser, IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

from django.shortcuts import get_object_or_404
from django.urls import reverse

from cart.models import Cart, CartItem
from main.models import Product
from cart.api import serializers

import random
import string

class CratItemCreateApiView(generics.CreateAPIView):
	permission_classes = [IsAuthenticated,]
	queryset = CartItem.objects.all()
	serializer_class = serializers.CartItemCreateSerializer

	def create(self, request, *args, **kwargs):
		serializer = self.get_serializer(data=request.data)
		if serializer.is_valid():
			if not Cart.objects.filter(user=request.user, checkout=False).exists():
				cart = Cart.objects.create(user=request.user, checkout=False)
			cart = Cart.objects.filter(user=request.user, checkout=False).first()
			product_id = serializer.data.get("product")
			product = get_object_or_404(Product, id=product_id)
			quantity = serializer.data.get("quantity")
			price = int(product.final_price.replace(",", "")) * quantity
			price = '{0:,}'.format(price)
			if not CartItem.objects.filter(cart=cart, product=product):
				cartitem = CartItem.objects.create(
							cart=cart,
							product=product,
							quantity=quantity,
							price=price,
						)
				result = "added"
			else:
				cartitem = CartItem.objects.filter(cart=cart, product=product).first()
				cartitem.quantity = quantity
				cartitem.price = price
				cartitem.save()
				result = f"updated with quantity {quantity}"
			response = {
				'status': 'success',
				'code': status.HTTP_200_OK,
				'message': f'Product in cart {result} successfully',
				'checkout' : request.build_absolute_uri(reverse('cart_api:cart_checkout')),
				}
			return Response(response)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class CratItemListApiView(generics.ListAPIView):
	permission_classes = [IsAuthenticated,]
	serializer_class = serializers.CartItemListSerializer

	def get_queryset(self):
		user = self.request.user
		cart = Cart.objects.filter(user=user, checkout=False).first()
		queryset = CartItem.objects.filter(cart=cart)
		return queryset

	def list(self, request, *args, **kwargs):
		response = super().list(request, *args, **kwargs)
		if not response.data :
			data = {
				'message' : 'Your cart is empty'
			}
			return Response(data,  status=status.HTTP_400_BAD_REQUEST)
		response = {
			'checkout' : request.build_absolute_uri(reverse('cart_api:cart_checkout')),
			'cartitems': response.data,
		}
		return Response(response)

class CartCheckOutApiView(APIView):
	permission_classes = [IsAuthenticated,]

	def get(self, request, *args, **kwargs):
		 # TODO: after banke payment clear cookie and checkout in cart = True
		 # Check Bank resalt ok than make code and clear history and save cart in checkout = True
		 # result = ?
		cart = get_object_or_404(Cart, user=request.user, checkout=False)
		key = "".join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12))
		cart.success_code = key
		cart.checkout = True
		cart.save()
		response = {
			'status': 'success',
			'code': status.HTTP_200_OK,
			'message': 'Checkout successfully',
			'success_code' : cart.success_code,
			}
		return Response(response)

class CartListApiView(generics.ListAPIView):
	permission_classes = [IsAuthenticated,]
	serializer_class = serializers.CartListSerializer

	def get_queryset(self):
		return Cart.objects.filter(user=self.request.user).order_by('-created')

class CartDetailApiView(generics.ListAPIView):
	permission_classes = [IsAuthenticated,]
	serializer_class = serializers.CartDetailSerializer

	def get_queryset(self):
		id = self.kwargs.get('id')
		cart = get_object_or_404(Cart, user=self.request.user, id=id)
		queryset = CartItem.objects.filter(cart=cart)
		return queryset

	def list(self, request, *args, **kwargs):
		response = super().list(request, *args, **kwargs)
		if not response.data :
			data = {
				'cart crete' : request.build_absolute_uri(reverse('cart_api:cart_create')),
				'message': 'This cart has not any products',
			}
			return Response(data,  status=status.HTTP_400_BAD_REQUEST)
		response = {
			'cartitems': response.data,
		}
		return Response(response)

cart/trash/views.py
from django.shortcuts import render, Http404, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

from main.models import *
from .models import *
from main.views import ModelsObjectMixin

import random
import string

class CartCreateView(View):
    template_name = 'cart_create.html'

    def get(self, request, *args, **kwargs):
        added_product = []
        context = {}
        products = []
        total_price = "0"
        count = 0
        static_cookie = ["csrftoken", "sessionid", "messages"]
        for cookie in request.COOKIES :
            if cookie not in static_cookie :
                instance = request.COOKIES[cookie].split(',')
                if not Product.objects.filter(id=int(instance[0])).exists() or not instance[1].isnumeric() or int(instance[1]) > 3 :
                    raise Http404(f'You added "{cookie}" to cookie, Invalid Cookie.')
                else :
                    count += 1
                    product = Product.objects.filter(id=instance[0]).first()
                    name = product.name
                    final_price = product.final_price
                    int_price = int(final_price.replace(",","")) * int(instance[1])
                    price = '{0:,}'.format(int_price)
                    total_price = int(total_price.replace(",","")) + int_price
                    total_price = '{0:,}'.format(total_price)

                    # add cookie to cartitem > login user
                    if request.user.is_authenticated:
                        if not Cart.objects.filter(user=request.user, checkout=False).exists():
                            cart = Cart.objects.create(user=request.user, checkout=False)
                        cart = Cart.objects.filter(user=request.user, checkout=False).first()
                        
                        if not CartItem.objects.filter(product=product, cart=cart) :
                            cartitem = CartItem.objects.create(
                                                product=product, 
                                                cart=cart,
                                                quantity=instance[1],
                                                price = price,
                                                )
                        else :
                            cartitem = CartItem.objects.filter(product=product, cart=cart).first()
                            cartitem.quantity = instance[1]
                            cartitem.price = price
                            cartitem.save()

                    added_product.append(product)
                    products.append({
                                    'product' : product, # product query
                                    'quantity' : instance[1], # quantity in cookie
                                    'price' : price,  # product.price * quantity
                                    })


        # this part checks item cart that if not in cookie
        if request.user.is_authenticated:
            for item in CartItem.objects.filter(cart=cart):
                if item.product not in added_product :
                    product = Product.objects.filter(name=item.product).first()
                    total_price = int(total_price.replace(",", "")) + int(item.price.replace(",", ""))
                    total_price = '{0:,}'.format(total_price)
                    products.append({
                                    'product' : product, 
                                    'quantity' : item.quantity, 
                                    'price' : item.price, 
                                    })


        if count == 0 :
            context = {
                    "empty" : True
            }
            return render(request, self.template_name, context)

        context["total_price"] = total_price
        context["products"] = products
        return render(request, self.template_name, context)

class CartCheckOutView(View):
    template_name = 'payment_result.html'

    @method_decorator(login_required(login_url='/account/login/'))
    def post(self, request, *args, **kwargs):
        ids = request.POST.get('id').split(",")
        quantity = request.POST.get('quantity').split(",")
        if not Cart.objects.filter(user=self.request.user, checkout=False).exists():
            cart = Cart.objects.create(user=self.request.user)
        cart = get_object_or_404(Cart, user=request.user, checkout=False)
        for id,quantity in zip(ids, quantity):
            product = get_object_or_404(Product, id=id)
            price = int(product.final_price.replace("," , "")) * int(quantity)
            price = '{0:,}'.format(price)
            cartitem = CartItem.objects.create(
                    cart = cart,
                    product = product,
                    quantity = int(quantity),
                    price = price,
            )
#     # TODO: after banke payment clear cookie and checkout in cart = True
#         # # TODO:  Check Bank resalt ok than make code and clear history and save cart in checkout = True
#         # result = ?  # TODO: chek api bank result True make code
        key = "".join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12))
        cart.success_code = key
        cart.checkout = True
        cart.save()
        context = {
                'result' : True,
                'code' : cart.success_code,
        }
        return render(request, self.template_name, context)

class CartHistoryView(ListView):
    template_name = 'cart_history.html'
    queryset = Cart.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = self.queryset.filter(user=self.request.user).order_by('-created')
        return queryset

class CartDetailView(ModelsObjectMixin, ListView):
    template_name = 'cart_detail.html'
    model = Cart
    queryset = CartItem.objects.all()

    def get_queryset(self):
        obj = self.get_object()
        queryset = super().get_queryset()
        queryset = self.queryset.filter(cart=obj.id)
        return queryset

cart/templates/cart_create.html
{% extends 'base.html' %}
{% load static %}

{% block headscript %}
<link rel="stylesheet" href="{% static '/css/cart.css' %}">
{% endblock %}

{% block content %}
<div class="container">
{% if empty %}
<h1> The cart has expired or product has not been added.  </h1>
{% else %}
<h1>Shopping Cart</h1>
<div class="shopping-cart">
  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Quantity</label>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Total</label>
  </div>
{% for product in products %}
  <div class="product">
    <div class="product-image">
      <img src="{{ product.product.image.url }}">
    </div>
    <div class="product-details">
      <div class="product-id">{{ product.product.id }}</div>
      <div class="product-title">{{ product.product.name }}</div>
      <p class="product-description"><span style="color:gray;"><strike>{{ product.product.initial_price }}</strike></span> - <span style="color:green;">%{{ product.product.off }}</span></p>
    </div>
    <div class="product-price">{{ product.product.final_price }}</div>
    <div class="product-quantity">
      <input class="quantity" type="number" value="{{ product.quantity }}" max="3" min="1">
    </div>
    <div class="product-removal">
      <button class="remove-product" value="{{ product.product.id }}" id="{{ product.product.name }}">
        Remove
      </button>
    </div>
    <div class="product-line-price">{{ product.price }}</div>
  </div>
{% endfor %}
  <div class="totals">
    <div class="totals-item totals-item-total">
      <label>Total Price</label>
      <div class="totals-value" id="cart-total">{{ total_price }}</div>
    </div>
  </div>
{% if user.is_authenticated %}
  <a href="{% url 'cart:checkout' %}" class="checkout" >  
    Check Out
  </a>
{% else %}
  <a href="{% url 'user:login' %}?next={{ request.get_full_path|urlencode }}" class="checkout" >  
    Login
  </a>
{% endif %}
</div>
{% endif %}
</div>

<script src="{% static '/js/cart_create.js' %}"></script>

{% endblock %}

cart/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}

{% block headscript %}
<link rel="stylesheet" href="{% static '/css/cart.css' %}">
{% endblock %}

{% block content %}
<div class="container">
<h1>Shopping Cart</h1>
<div class="shopping-cart">
  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Quantity</label>
    <label class="product-line-price">Total</label>
  </div>
{% for cartitem in object_list %}
  <div class="product">
    <div class="product-image">
      <img src="{{ cartitem.product.image.url }}">
    </div>
    <div class="product-details">

      <div class="product-title"><a href="{% url 'main:product_detail' id=cartitem.product.id %}" target="_blank">{{ cartitem.product.name }}</a></div>
      <p class="product-description"><span style="color:gray;"><strike>{{ cartitem.product.initial_price }}</strike></span> - <span style="color:green;">%{{ product.product.off }}</span></p>
    </div>
    <div class="product-price">{{ cartitem.product.final_price }}</div>
    <div class="product-quantity">
      {{ cartitem.quantity }}
    </div>
    <div class="product-line-price">{{ cartitem.price }}</div>
  </div>
{% endfor %}

    <div class="totals">
    <div class="totals-item totals-item-total">
      <label>Total Price</label>
      <div class="totals-value" id="cart-total">
        {% with object_list|first as first_cartitem %}{{ first_cartitem.cart.total_price }}{% endwith %}
    </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

cart/templates/cart_history.html
{% extends 'base.html' %}
{% load static %}

{% block headscript %}
<link rel="stylesheet" href="{% static '/css/cart.css' %}">
{% endblock %}

{% block content %}
<div class="container">
<h1>Cart History</h1>
<div class="shopping-cart">
  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Shopping Code</label>
    <label class="product-removal">Detail Cartitems</label>
    <label class="product-price">Checkout </label>
    <label class="product-quantity">Quantity</label>
    <label class="product-line-price">Total</label>
  </div>
{% for cart in object_list %}
{% if cart.checkout %}
  <div class="product">
    <div class="product-image">
      {{ forloop.counter }}
    </div>
    <div class="product-details">
      <div class="product-title">{{ cart.success_code }}</div>
    </div>
    <div class="product-removal"><a href="{% url 'cart:cart_detail' id=cart.id%}" target="_blank">Detail</a></div>
    <div class="product-price">{{ cart.checkout }}</div>
    <div class="product-quantity">
      {{ cart.total_item }}
    </div>
    <div class="product-line-price">{{ cart.total_price }}</div>
  </div>
  {% endif %}
{% endfor %}
</div>
</div>

{% endblock %}

cart/templates/payment_result.html
{% extends 'base.html' %}
{% load static %}

{% block headscript %}
<link rel="stylesheet" href="{% static '/css/cart.css' %}">
{% endblock %}

{% block content %}
<div class="container">
<h1>Result</h1>
{% if result %}
<center>
Result : {{ result }}
<br>
Your Sale Code : {{ code }}
<br><br><br>
<button class="btn btn-lg btn-primary" onclick="location.replace('{% url 'cart:cart_history' %}')">
  Cart History
</button>
{% else %}
<center>
Result : {{ result }}
<br>
Sorry , Try Again .
<button class="btn btn-lg btn-primary" onclick="location.replace('{% url 'cart:create' %}')">
  Back To Cart
</button>
{% endif %}
</center>

</div>

{% if result %}
<script>
  // clear all cookie after complete Payment
  var cookies = document.cookie.split(";");
  for(var i=0; i < cookies.length; i++) {
      var equals = cookies[i].indexOf("=");
      var name = equals > -1 ? cookies[i].substr(0, equals) : cookies[i];
      document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT"  + ";path=/";
  }
</script>
{% endif %}

{% endblock %}