ajax/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from ajax.views import (
                GetVaildNameView,
                GetVaildUserNameView,
)

urlpatterns = [
        path('check_name/', GetVaildNameView.as_view()),
        path('check_username/', GetVaildUserNameView.as_view()),
]

main/api/urls.py
from django.urls import path
from main.api import views


app_name = "main_api"

urlpatterns = [
        path('manaufacture_list/', views.ManufacturerListApiView.as_view(), name='manaufacture_list'),
        path('manaufacture_detail/<int:id>/', views.ManufacturerDetailApiView.as_view(), name='manaufacture_detail'),

        path('category_list/', views.CategoryListApiView.as_view(), name='category_list'),
        path('category_detail/<int:id>/', views.CategoryDetailApiView.as_view(), name='category_detail'),

        path('product_list/', views.ProductListApiView.as_view(), name='product_list'),
        path('product_detail/<int:id>/', views.ProductDetailApiView.as_view(), name='product_detail'),
        
        path('productbymanufacturer_list/<int:id>/', views.ProductListByManufacturerApiView.as_view(), name='productbymanufacturer_list'),
        path('productbycategory_list/<int:id>/', views.ProductListByCategoryApiView.as_view(), name='productbycategory_list'),
        path('productbytag_list/<str:name>/', views.ProductListByTagNameApiView.as_view(), name='productbytag_list'),

        path('tag_list/', views.TagsListApiView.as_view(), name='tag_list'),

]

main/urls.py
from django.urls import path
from .views import (
                TaggedView,

                ManufacturerListView,
                ManufacturerDetailView,
                ManufacturerCreateView,
                ManufacturerUpdateView,
                ManufacturerDeleteView,

                CategoryListView,
                CategoryCreateView,
                CategoryUpdateView,
                CategoryDeleteView,

                ProductListView,
                ProductDetailView,
                ProductCreateView,
                ProductUpdateView,
                ProductDeleteView,
)

app_name = "main"

urlpatterns = [
    # Tagged urls
    path('tag/<slug:slug>/', TaggedView.as_view(), name="tagged"),

    #  Product Urls
    path('product/list/',              ProductListView.as_view(),   name='product_list'),
    path('product/create/',            ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:id>/',   ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:id>/',   ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:id>/',   ProductDeleteView.as_view(), name='product_delete'),


    #  Category Urls
    path('category/list/',            CategoryListView.as_view(),   name='category_list'),
    path('category/create/',          CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:id>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:id>/', CategoryDeleteView.as_view(), name='category_delete'),

    #  Manufacturer Urls
    path('manufacturer/list/',            ManufacturerListView.as_view(),   name='manufacturer_list'),
    path('manufacturer/create/',          ManufacturerCreateView.as_view(), name='manufacturer_create'),
    path('manufacturer/detail/<int:id>/', ManufacturerDetailView.as_view(), name='manufacturer_detail'),
    path('manufacturer/update/<int:id>/', ManufacturerUpdateView.as_view(), name='manufacturer_update'),
    path('manufacturer/delete/<int:id>/', ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
]

main/api/views.py
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser, IsAuthenticated, AllowAny
from rest_framework.response import Response

from django.shortcuts import get_object_or_404
from django.db.models import Q

from main.api import serializers
from main.models import Manufacturer, Category, Product
from taggit.models import Tag

class ManufacturerListApiView(generics.ListAPIView):
	serializer_class = serializers.ManufacturerSerializer
	queryset = Manufacturer.objects.all()

class ManufacturerDetailApiView(generics.RetrieveAPIView):
	serializer_class = serializers.ManufacturerSerializer
	queryset = Manufacturer.objects.all()
	lookup_field = 'id'

class CategoryListApiView(generics.ListAPIView):
	serializer_class = serializers.CategorySerializer
	queryset = Category.objects.all()

class CategoryDetailApiView(generics.RetrieveAPIView):
	serializer_class = serializers.CategorySerializer
	queryset = Category.objects.all()
	lookup_field = 'id'

class ProductListApiView(generics.ListAPIView):
	serializer_class = serializers.ProductSerializer
	queryset = Product.objects.all()

class ProductDetailApiView(generics.RetrieveAPIView):
	serializer_class = serializers.ProductSerializer
	queryset = Product.objects.all()
	lookup_field = 'id'

class ProductListByManufacturerApiView(generics.ListAPIView):
	serializer_class = serializers.ProductSerializer
	lookup_field = 'id'

	def get_queryset(self):
		id = self.kwargs.get('id')
		self.queryset = Product.objects.filter(manufacturer__id=id)
		return super().get_queryset()

class ProductListByManufacturerApiView(generics.ListAPIView):
	serializer_class = serializers.ProductByManufacturerSerializer
	lookup_field = 'id'

	def get_queryset(self):
		id = self.kwargs.get('id')
		self.queryset = Product.objects.filter(manufacturer_id=id)
		return super().get_queryset()

class ProductListByCategoryApiView(generics.ListAPIView):
	serializer_class = serializers.ProductByCategorySerializer
	lookup_field = 'id'

	def get_queryset(self):
		id = self.kwargs.get('id')
		self.queryset = Product.objects.filter(category_id=id)
		return super().get_queryset()

class ProductListByTagNameApiView(generics.ListAPIView):
	serializer_class = serializers.ProductByTagSerializer
	lookup_field = 'name'

	def get_queryset(self):
		tag_name = self.kwargs.get('name')
		# tag = Tag.objects.filter(name=tag_name).first()
		tag = get_object_or_404(Tag, name=tag_name)
		self.queryset = Product.objects.filter(tags=tag)
		return super().get_queryset()


class TagsListApiView(generics.ListAPIView):
	serializer_class = serializers.TagSerializer
	queryset = Tag.objects.all()

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.template.defaultfilters import slugify
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from taggit.models import Tag
from .models import Manufacturer, Category, Product, MultipleImages
from .forms import (
        ManufacturerCreateForm,
        ManufacturerEditForm,
        CategoryModelForm,
        ProductCreateForm,
        ProductEditForm,
)

#  Tagging Class
class TaggedView(View):

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug', None)
        if slug :
            tag = get_object_or_404(Tag, slug=slug)
            context = {
                'common_tags' : Product.tags.most_common()[:8],
                'query' : Product.objects.filter(tags=tag).order_by('name'),
            }
            return render(request, 'tag.html', context)
        context = {}
        return render(request, 'tag.html', context)


# Model Id Class
class ModelsObjectMixin(object):

    def get_object(self):
        id = self.kwargs.get('id')
        obj = None
        if id is not None :
            obj = get_object_or_404(self.model, id=id)
        return obj

#  Product Classes
class ProductListView(ListView):
    template_name = "product/list.html"
    queryset = Product.objects.all()

class ProductDetailView(ModelsObjectMixin, DetailView):
    template_name = "product/detail.html"
    model = Product

class ProductCreateView(View):
    template_name = "product/create.html"

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        form = ProductCreateForm()
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = ProductCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new = form.save(commit=False)
            new.slug = slugify(new.name)
            multiple_images = request.FILES.getlist('multipleimages')
            new.save()
            form.save_m2m()
            for image in multiple_images:
                MultipleImages.objects.create(image=image, product_id=new.id)

            return redirect('main:product_detail', id=new.id)
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

class ProductUpdateView(ModelsObjectMixin, View):
    template_name = "product/update.html"
    model = Product

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        form = ProductEditForm(instance=obj)
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        form = ProductEditForm(request.POST, request.FILES, instance=obj)
        if form.is_valid():
            new_name = form.cleaned_data.get('new_name', None)
            edit = form.save(commit=False)
            if new_name :
                edit.name = new_name
            edit.save()
            form.save_m2m()
            clear_images = form.cleaned_data.get("clear_images")
            if clear_images:
                MultipleImages.objects.filter(product_id=edit.id).delete()
            multiple_images = request.FILES.getlist('multipleimages')
            if multiple_images :
                for image in multiple_images:
                    MultipleImages.objects.create(image=image, product_id=edit.id)
            return redirect('main:product_detail', id=obj.id)
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

class ProductDeleteView(ModelsObjectMixin, View):
    template_name = "product/delete.html"
    model = Product

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        context = {
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj:
            obj.delete()

            # delete unused tag after delete item
            Tag.objects.annotate(ntag=Count('taggit_taggeditem_items')).filter(ntag=0).delete()

        return redirect('main:product_list')


#  Category Classes
class CategoryListView(ListView):
    template_name = 'category/list.html'
    queryset = Category.objects.all()

class CategoryCreateView(View):
    template_name = 'category/create.html'

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        form = CategoryModelForm()
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = CategoryModelForm(request.POST)
        if form.is_valid():
            new = form.save()
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

class CategoryUpdateView(ModelsObjectMixin, View):
    template_name = "category/update.html"
    model = Category

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        form = CategoryModelForm(instance=obj)
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        form = CategoryModelForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

class CategoryDeleteView(ModelsObjectMixin, View):
    template_name = "category/delete.html"
    model = Category

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        context = {
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        context = {
                    'object' : obj,
        }
        if obj:
            obj.delete()
        return redirect('main:category_list')


#  Manufacturer Classes
class ManufacturerListView(ListView):
    template_name = "manufacturer/list.html"
    queryset = Manufacturer.objects.all()

class ManufacturerDetailView(ModelsObjectMixin, DetailView):
    template_name = "manufacturer/detail.html"
    model = Manufacturer

class ManufacturerCreateView(View):
    template_name = "manufacturer/create.html"

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        form = ManufacturerCreateForm()
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = ManufacturerCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new = form.save()
            return redirect('main:manufacturer_detail', id=new.id)
        context = {
                'form' : form,
        }
        return render(request, self.template_name, context)

class ManufacturerUpdateView(ModelsObjectMixin, View):
    template_name = "manufacturer/update.html"
    model = Manufacturer

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        form = ManufacturerEditForm(instance=obj)
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        form = ManufacturerEditForm(request.POST, request.FILES, instance=obj)
        if form.is_valid():
            new_name = form.cleaned_data.get('new_name', None)
            new = form.save(commit=False)
            if new_name :
                new.name = new_name
            new.save()
            return redirect('main:manufacturer_detail', id=obj.id)
        context = {
                    'form' : form,
                    'object' : obj,
        }
        return render(request, self.template_name, context)

class ManufacturerDeleteView(ModelsObjectMixin, View):
    template_name = "manufacturer/delete.html"
    model = Manufacturer

    @method_decorator(login_required(login_url='/account/login/'))
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        context = {
                    'object' : obj,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        context = {
                    'object' : obj,
        }
        if obj:
            obj.delete()
        return redirect('main:manufacturer_list')

main/templates/product/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <h1>Product Create Page</h1>
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% for field in form %}
         {% if 'Name' in field.label_tag %}
         {{ field }}
         <div class="valid-feedback">
           Product Ok !
         </div>
         <div class="invalid-feedback">
           Product Exists !
         </div>
         <br>
          {% elif 'tags' in field.label_tag %}
          <div class="form-group">
              <label>Tags :</label>
              <input type="text" data-role="tagsinput" class="form-control" name="tags">
          </div>
        {% elif 'Multipleimages' in field.label_tag%}
        <span style="color:blue;">Multiple Images :</span>
        {{ field }}<br>
         {% else %}
         {{ field }}<br><br>
         {% endif %}
         <br>
         <span id="message">
               {% for error in field.errors %}
               <div class="alert alert-warning" style="width:35%;">
                 {{ error }}
               </div>
               {% endfor %}
         </span>
       {% endfor %}
       <br><br>
    <input type="submit" value="Create">
  </form>
</div>

<script src="{% static 'js/easy-number-separator.js' %}"></script>
<script src="{% static '/js/validator.js' %}"></script>

<!-- tags input javascript codes -->
<script src="{% static 'js/tagsinput.js' %}"></script>

<script>

  $("#post-form").submit(function(e){
      e.preventDefault();
      });

</script>


{% endblock %}

main/templates/product/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h1>Product Delete Page</h1>
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    <h3>Delete {{ object }} ?</h3>
    <input type="submit" value="Delete">
    <a href="{% url 'main:product_list' %}">Cancel</a>
  </form>
</div>

{% endblock %}

main/templates/product/detail.html
{% extends 'base.html' %}
{% load multi_image %}

{% block content %}

<div class="container">
  <img src="{{ object.image.url }}" alt="" width="800" height="600">
  <br>
  {% images product as muliti_images %}
      {% if muliti_images %}
      {% for image in muliti_images %}
      <span><img src="/media/{{ image }}" width="100px" height="80px" class="zoom"></span>
      {% endfor %}
      {% else %}
      <span style="color:brown;" class="mx-4">No Multi Images Found</span>
      <br><br>
      {% endif %}
  <br><br>
  <div class="product-add">
    <button class="btn btn-success" title="Add To Cart" value="{{ product.id }}" id="{{ product.name }}">
      <i class="fas fa-shopping-cart"></i>
    </button>
  </div>
  <br><br>
  Name : {{ object.name }} <br>
  <small> {{ object.model }}</small> <br>
  {{ object.manufacturer }} / {{ object.category }} <br>
  Initial Price : {{ object.initial_price }}<br>
  Off : {{ object.off }}<br>
  Finall Price : {{ object.final_price }}<br>
  Create :{{ object.create }}<br>
  Update : {{ object.update }}<br>
  {% if user.is_staff %}
    Stock : {{ object.stock }}<br>
  {% endif %}
  {% if object.tags.all %}
  <div style="display:flex">
      {% for tag in object.tags.all|slice:"0:3" %}
      <a href="{% url 'main:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
      {% endfor %}
  </div>
  {% endif %}
  Content : <br> <p>{{ object.desc }}</p>
  <br><br><br><br>
</div>

<!-- javascript code for add product details to ccokie -->
<script>
  $('.product-add button').click( function() {
      var cname = $(this).attr('id');
      var cvalue = $(this).val();
      var d = new Date();
      d.setTime(d.getTime() + (24*60*60*1000));
      var expires = "expires=" + d.toGMTString();
      document.cookie = cname + "=" + [cvalue , '1'] + ";" + expires + ";path=/";
    });
</script>


{% endblock %}

main/templates/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
<h1>Products List Page</h1>
   <div class="row mb-3 posts" id="main">
     {% for instance in object_list %}
     <div class="col-md-3 main2">
         <div class="cards" >
             <div class="row no-gutters border rounded  flex-md-row mb-4 shadow-sm h-md-250">
               <div class="col p-4 d-flex flex-column">
                   <div style="display:flex">
                      <img src="{{ instance.image.url }}" width="200" height="150">
                   </div>
               </div>
                 <div class="col p-4 d-flex flex-column position-static">
                     <h3 class="my-1">
                       <a href="{% url 'main:product_detail' instance.id %}" target="_blank">
                       {{instance.name}}
                     </a>
                   </h3>
                     <p class="price">
                       {% if instance.manufacturer %}
                           <span style="color:lightblue;"><a href="{% url 'main:manufacturer_detail' id=instance.manufacturer.id %}" target="_blank">
                             {{ instance.manufacturer }}</a>
                           <span style="color:black;">/</span>
                         </span>
                       {% endif %}
                       {% if instance.category %}
                           <span style="color:blue;">{{ instance.category }}</span>
                       {% endif %}
                       {% if instance.tags.all %}
                       <div style="display:flex">
                           {% for tag in instance.tags.all|slice:"0:3" %}
                           <a href="{% url 'main:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                           {% endfor %}
                       </div>
                       {% else %}
                       <br><br>
                       {% endif %}
                     {% if instance.off != 0 %}
                     <p class="mb-auto text-muted"><strike style="text-decoration-color:red;"> $ {{instance.initial_price}} </strike></p>
                     <p class="mb-auto" style="color:red;">Off : {{instance.off}} %</p>
                     <p class="mb-auto" style="color:green;">$ {{instance.final_price}} <br><br></p>
                     {% else %}
                     <p class="mb-auto" style="color:green;"> $ {{instance.initial_price}} <br><br><br><br></p>
                     {% endif %}
                         <center>
                           <div class="product-add">
                             <button class="btn btn-success" title="Add To Cart" value="{{ instance.id }}" id="{{ instance.name }}">
                               <i class="fas fa-shopping-cart"></i>
                             </button>
                           </div>
                         {% if user.is_superuser %}
                           <div>
                           <br>
                           <a href="{% url 'main:product_update' id=instance.id %}">Update</a>
                           <a href="{% url 'main:product_delete' id=instance.id %}">Delete</a>
                           </div>
                         {% endif %}
                         </center>
                 </div>
             </div>
         </div>
     </div>
    {% endfor %}
  </div>
 </div>

<!-- javascript code for add product details to ccokie -->
 <script>
   $('.product-add button').click( function() {
       var cname = $(this).attr('id');
       var cvalue = $(this).val();
       var d = new Date();
       d.setTime(d.getTime() + (24*60*60*1000));
       var expires = "expires=" + d.toGMTString();
       document.cookie = cname + "=" + [cvalue , '1'] + ";" + expires + ";path=/";
     });
 </script>

{% endblock %}

main/templates/product/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <h1>Product Update Page</h1>
  <h3>Updating : <a href="{{ object.get_absolute_url }}">{{ object }} </a></h3>
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% for field in form %}
       {% if 'Multipleimages' in field.label_tag%}
       <span style="color:blue;">Multiple Images :</span>
       {{ field }}<br>
       {% elif 'Edit' in field.label_tag %}
       {{ field }}
       <div class="valid-feedback">
         Product Ok !
       </div>
       <div class="invalid-feedback">
         Product Exists !
       </div>
       <br>
       {% else %}
       {{ field }}<br><br>
       {% endif %}
       <br>
       <span id="message">
             {% for error in field.errors %}
             <div class="alert alert-warning" style="width:35%;">
               {{ error }}
             </div>
             {% endfor %}
       </span>
     {% endfor %}
    <br><br>
    <input type="submit" value="Update">
    <a href="{% url 'main:product_list' %}">Cancel</a>
  </form>
</div>

<script src="{% static 'js/easy-number-separator.js' %}"></script>
<script src="{% static '/js/validator.js' %}"></script>

<!-- tags input javascript codes -->
<script src="/static/js/tagsinput.js"></script>
<script>

$("#post-form").submit(function(e){
    e.preventDefault();
    });

</script>

{% endblock %}